language: java
jdk:
  - openjdk16

sudo: false

script: mvn clean package -DskipTests=true

after_success:
 - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -herimvsem@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
     - CODECOV_TOKEN="388fa5d7-d5b9-43da-a189-d90fbd991ff2"

deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
  app: mein-forum