## datasource
spring:
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
#    url: jdbc:postgresql://localhost:5432/forum
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
#    username: postgres
    password: sa
#    password: postgres
    driverClassName: org.h2.Driver
#    driverClassName: org.postgresql.Driver

logging:
  level:
    org.springframework.web: DEBUG
    ru.job4j.forum.controller: DEBUG
    org.hibernate: DEBUG
    org: INFO
